User.create!([
  {id: 1,    name: 'Hibasan2105',    email: 'test01@email.com',    password: 'password',    password_confirmation: 'password',    confirmed_at: Time.now,    admin: true  },
  {id: 2,    name: 'おめがリオ',    email: 'test02@email.com',    password: 'password',    password_confirmation: 'password',    confirmed_at: Time.now,    admin: false  },
  {id: 3,    name: 'おめがレイ',    email: 'test03@email.com',    password: 'password',    password_confirmation: 'password',    confirmed_at: Time.now,    admin: false  },
  {id: 4,    name: 'あるふぁライ',    email: 'test04@email.com',    password: 'password',    password_confirmation: 'password',    confirmed_at: Time.now,    admin: false  },
  {id: 5,    name: 'あるふぁロイ',    email: 'test05@email.com',    password: 'password',    password_confirmation: 'password',    confirmed_at: Time.now,    admin: false  }
  ])

Facility.create!([
  {id: 1, name: 'お風呂の国', prefecture: '神奈川県', address: '横浜市鶴見区下末吉２丁目２５−２３',
    homepage: 'http://www.ofuronokuni.co.jp/', business_hours: '11時00分〜24時00分', holiday: '',
    fee: '750円', payment: '現金', comment: ''},
  {id: 2, name: 'ヌーランドさがみ湯', prefecture: '東京都', address: '大田区仲六郷２丁目７−５',
    homepage: 'http://www.nu-land.com/', business_hours: '11時00分〜23時00分', holiday: '',
    fee: '1250円', payment: '現金', comment: ''},
  {id: 3, name: 'RAKU SPA 鶴見', prefecture: '神奈川県', address: '横浜市鶴見区元宮２丁目１−３９',
    homepage: 'http://rakuspa.com/tsurumi/', business_hours: '10時00分〜20時00分', holiday: '',
    fee: '1480円', payment: '現金', comment: ''},
  {id: 4, name: 'ヨコヤマ・ユーランド鶴見', prefecture: '神奈川県', address: '横浜市鶴見区下末吉２丁目２１',
    homepage: 'http://www.yu-land.com/', business_hours: '10時00分〜20時00分', holiday: '',
    fee: '1900円', payment: '現金', comment: ''},
  {id: 5, name: '川崎ビッグ', prefecture: '神奈川県', address: '川崎市川崎区小川町１５−１１',
    homepage: 'http://www.kawasaki-big.com/', business_hours: '24時間営業', holiday: '水曜日',
    fee: '1100円〜', payment: '現金', comment: ''},
  {id: 6, name: '天然温泉 平和島', prefecture: '東京都', address: '大田区平和島１丁目１−１',
    homepage: 'http://www.heiwajima-onsen.jp/', business_hours: '10時00分〜20時00分', holiday: '',
    fee: '2000円〜', payment: '現金', comment: ''},
  {id: 7, name: 'スパリゾートプレジデント', prefecture: '東京都', address: '台東区上野３丁目２８−６',
    homepage: 'https://sparesortpresident.com/', business_hours: '24時間営業', holiday: '水曜日',
    fee: '1200円〜', payment: '現金', comment: ''},
  {id: 8, name: 'サウナ&カプセルホテル北欧', prefecture: '東京都', address: '台東区上野７丁目２−１６',
    homepage: 'https://www.saunahokuou.com/?utm_source=google&utm_medium=map', business_hours: '24時間営業', holiday: '水曜日',
    fee: '1400円〜', payment: '現金', comment: ''},
  {id: 9, name: 'オアシスサウナ アスティル', prefecture: '東京都', address: '港区新橋３丁目１２−３',
    homepage: 'http://www.oasissauna.jp/', business_hours: '12時00分〜10時00分', holiday: '水曜日',
    fee: '1480円〜', payment: '現金', comment: ''},
  {id: 10, name: 'かるまる 池袋店（サウナ&ホテル）', prefecture: '東京都', address: '豊島区池袋２丁目７−７',
    homepage: 'https://karumaru.jp/ikebukuro/?utm_source=google&utm_medium=maps', business_hours: '11時00分〜10時00分', holiday: '水曜日',
    fee: '2980円〜', payment: '現金', comment: ''},
  {id: 11, name: '朝日湯源泉 ゆいる', prefecture: '神奈川県', address: '川崎市川崎区鋼管通３丁目１−２',
    homepage: 'http://asahiyu1010.com/', business_hours: '10時00分〜23時00分', holiday: '水曜日',
    fee: '1540円〜', payment: '現金', comment: ''},
  {id: 12, name: '朝日湯源泉 ゆいる', prefecture: '神奈川県', address: '川崎市川崎区鋼管通３丁目１−２',
    homepage: 'http://asahiyu1010.com/', business_hours: '10時00分〜23時00分', holiday: '水曜日',
    fee: '1540円〜', payment: '現金', comment: ''},
  {id: 13, name: '宮前平源泉 湯けむりの庄', prefecture: '神奈川県', address: '川崎市宮前区宮前平２丁目１３−３',
    homepage: 'https://www.yukemurinosato.com/miyamaedaira/', business_hours: '10時00分〜20時00分', holiday: '水曜日',
    fee: '1320円〜', payment: '現金', comment: ''},
  {id: 14, name: '宮前平源泉 湯けむりの庄', prefecture: '神奈川県', address: '川崎市宮前区宮前平２丁目１３−３',
    homepage: 'https://www.yukemurinosato.com/miyamaedaira/', business_hours: '10時00分〜20時00分', holiday: '水曜日',
    fee: '1320円〜', payment: '現金', comment: ''},
  {id: 15, name: 'スパ・リブール ヨコハマ', prefecture: '神奈川県', address: '横浜市鶴見区獅子ケ谷２丁目３９−１８',
    homepage: 'https://www.libur.co.jp/', business_hours: '10時00分〜8時00分', holiday: '水曜日',
    fee: '1520円〜', payment: '現金', comment: ''},
  {id: 16, name: '綱島源泉湯けむりの庄', prefecture: '神奈川県', address: '横浜市港北区樽町３丁目７−６１',
    homepage: 'http://yukemurinosato.com/tsunashima?utm_source=google&utm_medium=gmb', business_hours: '9時00分〜20時00分', holiday: '水曜日',
    fee: '1320円〜', payment: '現金', comment: ''},
  {id: 17, name: 'おふろの王様 大井町店', prefecture: '東京都', address: '品川区大井１丁目５０−５',
    homepage: 'http://www.ousama2603.com/shop/ooimachi/', business_hours: '9時30分〜20時00分', holiday: '水曜日',
    fee: '1380円〜', payment: '現金', comment: ''},
  {id: 18, name: 'みうら湯', prefecture: '神奈川県', address: '横浜市南区中里１丁目２５−１',
    homepage: 'http://www.miurayu.com/', business_hours: '10時00分〜20時00分', holiday: '水曜日',
    fee: '820円〜', payment: '現金', comment: ''},
  {id: 19, name: '萩の湯', prefecture: '東京都', address: '台東区根岸２丁目１３−１３',
    homepage: 'http://haginoyu.jp/', business_hours: '6時00分〜9時00分,11時00分〜1時00分', holiday: '水曜日',
    fee: '480円〜', payment: '現金', comment: ''},
  {id: 20, name: '両国湯屋 江戸遊', prefecture: '東京都', address: '墨田区亀沢１丁目５−８',
    homepage: 'https://www.edoyu.com/ryougoku/', business_hours: '10時00分〜20時00分', holiday: '水曜日',
    fee: '2750円〜', payment: '現金', comment: ''},
  ])
